name: nostr_dart
description: A library for nostr protocol implemented in dart for flutter
version: 1.0.0
homepage: https://github.com/0xchat-app/nostr-dart

environment:
  sdk: '>=2.18.5 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  bip340: ^0.1.0
  convert: ^3.1.1
  crypto: ^3.0.2

  pointycastle: ^3.3.0
  kepler: ^1.0.3
  http: ^0.13.3
  bech32: ^0.2.0



